#!/bin/bash

font_url="https://github.com/romkatv/powerlevel10k-media/raw/master"
font_local_dir="$HOME/Library/Fonts"
font_name="MesloLGS NF"
font_name_url_encoded="${font_name/\ /%20}"
declare -a font_styles=("Bold Italic" "Bold" "Italic" "Regular")
for font_style in "${font_styles[@]}"
do
  font_style_url_encoded="${font_style/\ /%20}"
  curl -L "$font_url/$font_name_url_encoded%20$font_style_url_encoded.ttf" -o "$font_local_dir/$font_name $font_style.ttf"
done
echo "🔧 Meslo Nerd Font is installed (required by Powerlevel10k)"

# Antibody https://getantibody.github.io
brew install antibody

ln -fs $PWD/zsh/p10k.zsh.symlink $HOME/.p10k.zsh
ln -fs $PWD/zsh/zsh_plugins.txt.symlink $HOME/.zsh_plugins.txt
ln -fs $PWD/zsh/zshrc.symlink $HOME/.zshrc
echo "🔗 Symbolic links for Zsh are created"
