tap "homebrew/cask"

cask "adobe-creative-cloud"
cask "craftmanager"
cask "docker"
cask "dropbox"
cask "firefox"
cask "google-chrome"
cask "iterm2"
cask "java"
cask "kap"
cask "keka"
cask "libreoffice"
cask "little-snitch"
cask "openoffice"
cask "quodlibet"
cask "sketch"
cask "steam"
cask "sublime-merge"
cask "sublime-text"
cask "teamspeak-client"
cask "vlc"

brew "asdf"
brew "composer"
brew "coreutils"
brew "docker-compose"
brew "git-lfs"
brew "gpg"
brew "jesseduffield/lazydocker/lazydocker"
brew "jq"
brew "mas"
brew "ssh-copy-id"
brew "yarn"

mas "Numbers", id: 409203825
mas "Pocket", id: 568494494
