#!/bin/zsh

# 📝 asdf plugin list: https://asdf-vm.com/#/plugins-all?id=plugin-list

# Hugo https://bitbucket.org/mgladdish/asdf-gohugo
asdf plugin-add gohugo

# Node.js https://github.com/asdf-vm/asdf-nodejs
asdf plugin-add nodejs
bash -c "${ASDF_DATA_DIR:=$HOME/.asdf}/plugins/nodejs/bin/import-release-team-keyring"

# Python https://github.com/danhper/asdf-python
asdf plugin-add python

# Ruby https://github.com/asdf-vm/asdf-ruby
asdf plugin-add ruby

# Yarn https://github.com/twuni/asdf-yarn
asdf plugin-add yarn
